// <auto-generated />
using System;
using DigitalBooking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalBooking.Infrastructure.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20251225011711_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalBooking.Domain.Attendance", b =>
                {
                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Appeared")
                        .HasColumnType("boolean")
                        .HasColumnName("appeared");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.HasKey("BookingId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookingAssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_asset_id");

                    b.Property<DateTime>("BookingEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("booking_end");

                    b.Property<string>("BookingNote")
                        .HasColumnType("text")
                        .HasColumnName("booking_note");

                    b.Property<DateTime>("BookingStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("booking_start");

                    b.Property<Guid?>("CancelledById")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_id");

                    b.Property<long>("ClassroomId")
                        .HasColumnType("bigint")
                        .HasColumnName("classroom_id");

                    b.Property<long?>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("meeting_link");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("PersonBookedId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_booked_id");

                    b.Property<Guid>("ResponsiblePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_person");

                    b.HasKey("Id");

                    b.HasIndex("BookingAssetId");

                    b.HasIndex("CancelledById");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("LessonId");

                    b.HasIndex("PersonBookedId");

                    b.HasIndex("ResponsiblePersonId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.BookingAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("RRule")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rrule");

                    b.Property<TimeSpan?>("RepeatDuration")
                        .HasColumnType("interval")
                        .HasColumnName("repeat_duration");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("booking_assets", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Classroom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("BookingSlotsLimit")
                        .HasColumnType("smallint")
                        .HasColumnName("booking_slots_limit");

                    b.Property<short?>("Capacity")
                        .HasColumnType("smallint")
                        .HasColumnName("capacity");

                    b.Property<long>("ClassroomTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("classroom_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OwnerDepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_department_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomTypeId");

                    b.HasIndex("OwnerDepartmentId");

                    b.ToTable("classrooms", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.ClassroomType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.ToTable("classroom_types", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long?>("ReplyToId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_id");

                    b.Property<Guid>("ReplyToPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to_post_id");

                    b.Property<Guid>("ReplyToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ReplyToId");

                    b.HasIndex("ReplyToPostId");

                    b.HasIndex("ReplyToUserId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Discipline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("disciplines", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("EnrollmentYear")
                        .HasColumnType("smallint")
                        .HasColumnName("enrollment_year");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("group_type");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("institute");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("number");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("prefix");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("speciality");

                    b.HasKey("Id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DisciplineId")
                        .HasColumnType("bigint")
                        .HasColumnName("discipline_id");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<string>("LmsLink")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lms_link");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("DisciplineId", "TeacherId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("ux_lessons_discipline_teacher_group");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.LessonMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Files")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("files")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "CreatedAt")
                        .HasDatabaseName("ix_lesson_materials_lesson_created_at");

                    b.ToTable("lesson_materials", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.LibrarySpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("ContentKey")
                        .HasColumnType("uuid")
                        .HasColumnName("content_key");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("PreviewKey")
                        .HasColumnType("uuid")
                        .HasColumnName("preview_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("library_space", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean")
                        .HasColumnName("read");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ReceiverId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_receiver_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<long?>("DisciplineId")
                        .HasColumnType("bigint")
                        .HasColumnName("discipline_id");

                    b.Property<string>("Files")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("files")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_posts_created_at");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_posts_tags_gin");

                    b.HasIndex("DisciplineId", "CreatedAt")
                        .HasDatabaseName("ix_posts_discipline_created_at");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.StudentProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactLink")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_link");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("student_profile", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.TeacherProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AcademicDegree")
                        .HasColumnType("text")
                        .HasColumnName("academic_degree");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ScienceCloudLink")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("science_cloud_link");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("teacher_profile", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("STUDENT")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_email");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DigitalBooking.Domain.Attendance", b =>
                {
                    b.HasOne("DigitalBooking.Domain.Booking", "Booking")
                        .WithMany("Attendance")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.User", "User")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Booking", b =>
                {
                    b.HasOne("DigitalBooking.Domain.BookingAsset", "BookingAsset")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalBooking.Domain.User", "CancelledBy")
                        .WithMany("BookingsCancelled")
                        .HasForeignKey("CancelledById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalBooking.Domain.Classroom", "Classroom")
                        .WithMany("Bookings")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.Lesson", "Lesson")
                        .WithMany("Bookings")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalBooking.Domain.User", "PersonBooked")
                        .WithMany("BookingsAsPersonBooked")
                        .HasForeignKey("PersonBookedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.User", "ResponsiblePerson")
                        .WithMany("BookingsAsResponsiblePerson")
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingAsset");

                    b.Navigation("CancelledBy");

                    b.Navigation("Classroom");

                    b.Navigation("Lesson");

                    b.Navigation("PersonBooked");

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("DigitalBooking.Domain.BookingAsset", b =>
                {
                    b.HasOne("DigitalBooking.Domain.User", "Owner")
                        .WithMany("BookingAssets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Classroom", b =>
                {
                    b.HasOne("DigitalBooking.Domain.ClassroomType", "ClassroomType")
                        .WithMany("Classrooms")
                        .HasForeignKey("ClassroomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.Department", "OwnerDepartment")
                        .WithMany("Classrooms")
                        .HasForeignKey("OwnerDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassroomType");

                    b.Navigation("OwnerDepartment");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Comment", b =>
                {
                    b.HasOne("DigitalBooking.Domain.User", "Creator")
                        .WithMany("CommentsCreated")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.Comment", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalBooking.Domain.Post", "ReplyToPost")
                        .WithMany("Comments")
                        .HasForeignKey("ReplyToPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.User", "ReplyToUser")
                        .WithMany("CommentsRepliedToUser")
                        .HasForeignKey("ReplyToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("ReplyTo");

                    b.Navigation("ReplyToPost");

                    b.Navigation("ReplyToUser");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Lesson", b =>
                {
                    b.HasOne("DigitalBooking.Domain.Discipline", "Discipline")
                        .WithMany("Lessons")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.Group", "Group")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.User", "Teacher")
                        .WithMany("LessonsTaught")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Group");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DigitalBooking.Domain.LessonMaterial", b =>
                {
                    b.HasOne("DigitalBooking.Domain.Lesson", "Lesson")
                        .WithMany("LessonMaterials")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DigitalBooking.Domain.LibrarySpace", b =>
                {
                    b.HasOne("DigitalBooking.Domain.User", "Creator")
                        .WithMany("LibrarySpaces")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Notification", b =>
                {
                    b.HasOne("DigitalBooking.Domain.Booking", "Booking")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalBooking.Domain.User", "Receiver")
                        .WithMany("Notifications")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Post", b =>
                {
                    b.HasOne("DigitalBooking.Domain.User", "Creator")
                        .WithMany("Posts")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.Discipline", "Discipline")
                        .WithMany("Posts")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("DigitalBooking.Domain.StudentProfile", b =>
                {
                    b.HasOne("DigitalBooking.Domain.Group", "Group")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalBooking.Domain.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("DigitalBooking.Domain.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalBooking.Domain.TeacherProfile", b =>
                {
                    b.HasOne("DigitalBooking.Domain.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("DigitalBooking.Domain.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalBooking.Domain.User", b =>
                {
                    b.HasOne("DigitalBooking.Domain.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Booking", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("DigitalBooking.Domain.BookingAsset", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Classroom", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DigitalBooking.Domain.ClassroomType", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Department", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Discipline", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Group", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Lesson", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LessonMaterials");
                });

            modelBuilder.Entity("DigitalBooking.Domain.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DigitalBooking.Domain.User", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("BookingAssets");

                    b.Navigation("BookingsAsPersonBooked");

                    b.Navigation("BookingsAsResponsiblePerson");

                    b.Navigation("BookingsCancelled");

                    b.Navigation("CommentsCreated");

                    b.Navigation("CommentsRepliedToUser");

                    b.Navigation("LessonsTaught");

                    b.Navigation("LibrarySpaces");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
