services:
  tempo-init:
    image: busybox
    command: [ "sh", "-c", "mkdir -p /var/tempo/traces && chown -R 10001:10001 /var/tempo" ]
    volumes:
      - digitalbooking-tempo-data:/var/tempo
    restart: "no"

  tempo:
    container_name: digitalbooking-tempo
    restart: unless-stopped
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
      - digitalbooking-tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "4317"        # OTLP gRPC (внутренний)
    networks:
      - digitalbooking-network
    depends_on:
      tempo-init:
        condition: service_completed_successfully

volumes:
  digitalbooking-tempo-data: