FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

RUN dotnet tool install --global dotnet-ef --version 10.0.*
ENV PATH="$PATH:/root/.dotnet/tools"

COPY DigitalBooking.sln ./
COPY DigitalBooking.Infrastructure/DigitalBooking.Infrastructure.csproj ./DigitalBooking.Infrastructure/
COPY DigitalBooking.Presentation/DigitalBooking.Presentation.csproj ./DigitalBooking.Presentation/
COPY DigitalBooking.Application/DigitalBooking.Application.csproj ./DigitalBooking.Application/
COPY DigitalBooking.Domain/DigitalBooking.Domain.csproj ./DigitalBooking.Domain/

RUN dotnet restore DigitalBooking.sln -r linux-x64

COPY . .

RUN dotnet ef migrations bundle \
    --project DigitalBooking.Infrastructure/DigitalBooking.Infrastructure.csproj \
    --startup-project DigitalBooking.Presentation/DigitalBooking.Presentation.csproj \
    --context DigitalBooking.Infrastructure.DbContext \
    --configuration Release \
    --self-contained \
    --output /app/efbundle

FROM mcr.microsoft.com/dotnet/runtime-deps:10.0
WORKDIR /app
COPY --from=build /app/efbundle ./efbundle
RUN chmod +x ./efbundle

ENTRYPOINT ["sh", "-c", "./efbundle --connection \"$CONNECTION_STRING\""]
